baseURL = "https://fresh-test.netlify.app/"
languageCode = "en-us"
title = "Fresh"

themesDir = "themes"
theme = "furn"

[params]
    currencySymbol = "$"

[taxonomies]
    category = "products"

[build]
    writeStats = true